export default {
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
  GET_FEED_START: 'GET_FEED_START',
  GET_FEED_SUCCESS: 'GET_FEED_SUCCESS',
  GET_FEED_FAILURE: 'GET_FEED_FAILURE',
};
